### ISSUE TITLE
Invalid Swagger output

### ISSUE THREAD

**Issue by IvanGoncharov** [bobby-brennan/kaltura-spec-converter#1]
Please use `validate` method: 
https://github.com/lucybot/api-spec-converter/blob/master/lib/base-type.js#L30

``` yaml
- code: ONE_OF_MISSING
  inner:
    - code: ONE_OF_MISSING
      inner:
        - code: OBJECT_MISSING_REQUIRED_PROPERTY
          message: 'Missing required property: schema'
          path: []
        - code: ONE_OF_MISSING
          inner:
            - code: OBJECT_ADDITIONAL_PROPERTIES
              message: 'Additional properties not allowed: x_df_default,enumLabels'
              path: []
            - code: OBJECT_ADDITIONAL_PROPERTIES
              message: 'Additional properties not allowed: x_df_default,enumLabels'
              path: []
            - code: OBJECT_ADDITIONAL_PROPERTIES
              message: 'Additional properties not allowed: x_df_default,enumLabels'
              path: []
            - code: OBJECT_MISSING_REQUIRED_PROPERTY
              message: 'Missing required property: required'
              path: []
          message: "Data does not match any schemas from 'oneOf'"
          path: []
      message: "Data does not match any schemas from 'oneOf'"
      path:
        - paths
        - /service/xinternal/action/xAddBulkDownload
        - get
        - parameters
        - '0'
    - code: OBJECT_MISSING_REQUIRED_PROPERTY
      message: 'Missing required property: $ref'
      path:
        - paths
        - /service/xinternal/action/xAddBulkDownload
        - get
        - parameters
        - '0'
  message: Not a valid parameter definition
  path:
    - paths
    - /service/xinternal/action/xAddBulkDownload
    - get
    - parameters
    - '0'
```
